### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by ryanyu512** [ducha-aiki/hesaff-pytorch#3]
Hi, 

I have tried to run the command: python extract_features_oxaff.py graf1.ppm out.txt 2000. I got the following error:
Traceback (most recent call last):
  File "extract_features_oxaff.py", line 36, in <module>
    LAFs, resp  = HA(var_image)
  File "/home/ryan/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ryan/hessian_affine_local_feature_detector/hesaff-pytorch-master/SparseImgRepresenter.py", line 200, in forward
    responses, LAFs, final_pyr_idxs, final_level_idxs = self.multiScaleDetector(x,num_features_prefilter)
  File "/home/ryan/hessian_affine_local_feature_detector/hesaff-pytorch-master/SparseImgRepresenter.py", line 84, in multiScaleDetector
    scales = sigmas_oct[level_idx - 1:level_idx + 2])
  File "/home/ryan/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ryan/hessian_affine_local_feature_detector/hesaff-pytorch-master/HandCraftedModules.py", line 253, in forward
    num_of_nonzero_responces = (nmsed_resp > 0).sum().data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

Do you know the reasons for this error? 

Thanks

**Comment by ducha-aiki** [comment]
Yes. In pytorch1.0  or like this, they dropped support of accessing single-item-tensor as data[0] in favor of .item(), as it is stated in error message. 

This repo was created with 0.4.0 version of pytorch
